// LOGIN

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT = "LOGOUT";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const REFRESH_ACCESSTOKEN = "REFRESH_ACCESSTOKEN";
export const VERIFY_ACCOUNT = "VERIFY_ACCOUNT";

// ACCESSTOKEN
export const ACCESSTOKEN_REQUEST = "ACCESSTOKEN_REQUEST";
export const ACCESSTOKEN_SUCCESS = "ACCESSTOKEN_SUCCESS";
export const ACCESSTOKEN_FAIL = "ACCESSTOKEN_FAIL";

//MOVIES
export const REQUESTMOVIES = "REQUESTMOVIES";
export const REQUESTGETMOVIES = "REQUESTGETMOVIES";
export const REQUESTGETALLMOVIE = "REQUESTGETALLMOVIE";
export const REQUESTGETMOVIE = "REQUESTGETMOVIE";
export const REQUESTDELETEMOVIES = "REQUESTDELETEMOVIES";
export const REQUESTUPDATEMOVIES = "REQUESTUPDATEMOVIES";
export const REQUESTINSERTMOVIE = "REQUESTINSERTMOVIE";
export const REQUESTFAILMOVIES = "REQUESTFAILMOVIES";

//CATEGORY
export const REQUESCATEGORY = "REQUESCATEGORY";
export const GETCATEGORYPUBLIC = "GETCATEGORYPUBLIC";
export const GETCATEGORY = "GETCATEGORY";
export const INSERTCATEGORY = "INSERTCATEGORY";
export const UPDATECATEGORY = "UPDATECATEGORY";
export const DELETECATEGORY = "DELETECATEGORY";
export const FAILCATEGORY = "FAILCATEGORY";


//MYLIST
export const REQUESTMYLIST = "REQUESTMYLIST";
export const REQUESTSECCESSMYLIST = "REQUESTSECCESSMYLIST";
export const INSERTMYLIST = "INSERTMYLIST";
export const REQUESTFAILDMYLIST = "REQUESTFAILDMYLIST";
export const REMOVEMYLIST = "REMOVEMYLIST";


//COMMENT
export const REQUESTCOMMENT = "REQUESTCOMMENT";
export const SUCCESSCOMENT = "SUCCESSCOMENT";
export const FAILDCOMMENT = "FAILDCOMMENT";
export const INSERTCOMMENT = "INSERTCOMMENT";
export const DELETECOMMENT = "DELETECOMMENT";

//RATING
export const REQUESTRATING = "REQUESTRATING";
export const SUCCESSRATING = "SUCCESSRATING";
export const FAILDRATING = "FAILDRATING";
export const INSERTRATING = "INSERTRATING";

//Users
export const REQUESTUSER = "REQUESTUSER";
export const GETUSERS = "GETUSERS";
export const GETUSER = "GETUSER";
export const INCERTUSER = "INCERTUSER";
export const UPDATEUSER = "UPDATEUSER";
export const DELETEUSER = "DELETEUSER";
export const FAILREQUESTUSER = "FAILREQUESTUSER";

//payment
export const REQUESTPAYMENT = "REQUESTPAYMENT";
export const SUCCESSPAYMENT = "SUCCESSPAYMENT";
export const GETPAYMENT = "GETPAYMENT";
export const INSERTPAYMENT = "INSERTPAYMENT";
export const FAILDPAYMENT = "FAILDPAYMENT";

//SIDEBARTOGGLE

export const CLOSESIDEBAR = "CLOSESIDEBAR";
export const OPENSIDEBAR = "OPENSIDEBAR";
