// LOGIN

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT="LOGOUT";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const REFRESH_ACCESSTOKEN = "REFRESH_ACCESSTOKEN";
export const VERIFY_ACCOUNT = "VERIFY_ACCOUNT";

// ACCESSTOKEN
export const ACCESSTOKEN_REQUEST = "ACCESSTOKEN_REQUEST";
export const ACCESSTOKEN_SUCCESS = "ACCESSTOKEN_SUCCESS";
export const ACCESSTOKEN_FAIL = "ACCESSTOKEN_FAIL";

//POPULER
export const REQUESTMOVIE = "REQUESTMOVIE";
export const REQUESTSUCCESSMOVIE = "REQUESTSUCCESSMOVIE";
export const REQUESTFAILMOVIE = "REQUESTFAILMOVIE";

//TOPRATED
export const REQUESTTOPRATED = "REQUESTTOPRATED";
export const REQUESTSUCCESSTOPRATED = "REQUESTSUCCESSTOPRATED";
export const REQUESTFAILTOPRATED = "REQUESTFAILTOPRATED";

//fetchActionMovies
export const REQUESTACTIONMOVIES = "REQUESTACTIONMOVIES";
export const REQUESTSUCCESSACTIONMOVIES = "REQUESTSUCCESSACTIONMOVIES";
export const REQUESTFAILACTIONMOVIES = "REQUESTFAILACTIONMOVIES";

//fetchComedyMovies
export const REQUESTCOMEDYMOVIES = "REQUESTCOMEDYMOVIES";
export const REQUESTSUCCESSCOMEDYMOVIES = "REQUESTSUCCESSCOMEDYMOVIES";
export const REQUESTFAILCOMEDYMOVIES = "REQUESTFAILCOMEDYMOVIES";

//fetchHorrorMovies
export const REQUESTHORRORMOVIES = "REQUESTHORRORMOVIES";
export const REQUESTSUCCESSHORRORMOVIES = "REQUESTSUCCESSHORRORMOVIES";
export const REQUESTFAILHORRORMOVIES = "REQUESTFAILHORRORMOVIES";

//fetchRomanceMovies
export const REQUESTROMANCEMOVIES = "REQUESTROMANCEMOVIES";
export const REQUESTSUCCESSROMANCEMOVIES = "REQUESTSUCCESSROMANCEMOVIES";
export const REQUESTFAILROMANCEMOVIES = "REQUESTFAILROMANCEMOVIES";
//fetchRomanceMovies
export const REQUESTMYLIST = "REQUESTMYLIST";
export const REQUESTSECCESSMYLIST = "REQUESTSECCESSMYLIST";
export const REQUESTFAILDMYLIST = "REQUESTFAILDMYLIST";
export const INSERTMYLIST = "INSERTMYLIST";
export const REMOVEMYLIST = "REMOVEMYLIST";

//COMMENT
export const REQUESTCOMMENT = "REQUESTCOMMENT";
export const SUCCESSCOMENT = "SUCCESSCOMENT";
export const FAILDCOMMENT = "FAILDCOMMENT";
export const INSERTCOMMENT = "INSERTCOMMENT";

//RATING
export const REQUESTRATING = "REQUESTRATING";
export const SUCCESSRATING = "SUCCESSRATING";
export const FAILDRATING = "FAILDRATING";
export const INSERTRATING = "INSERTRATING";

//Users
export const REQUESTUSER = "REQUESTUSER";
export const GETUSERS = "GETUSERS";
export const GETUSER = "GETUSER";
export const INCERTUSER = "INCERTUSER";
export const UPDATEUSER = "UPDATEUSER";
export const DELETEUSER = "DELETEUSER";
export const FAILREQUESTUSER = "FAILREQUESTUSER";

//payment
export const REQUESTPAYMENT = "REQUESTPAYMENT";
export const SUCCESSPAYMENT = "SUCCESSPAYMENT";
export const GETPAYMENT = "GETPAYMENT";
export const INSERTPAYMENT = "INSERTPAYMENT";
export const FAILDPAYMENT = "FAILDPAYMENT";

//SIDEBARTOGGLE

export const CLOSESIDEBAR="CLOSESIDEBAR";
export const OPENSIDEBAR="OPENSIDEBAR";
